### ISSUE TITLE
[3월] 스터디 회고 

### ISSUE THREAD

**Issue by junho112** [SSAFY0916/Algorithm_Study_Java_C#19]
3월 결과 보고서 작성을 위해 스터디를 진행하는 동안의 느낀점이나, 앞으로의 스터디다짐 등을 자유롭게 공유해주세요!!! 
기한 : (~03/29)
최소 길이 : 2줄 이상 
최대 길이 ; 자유

**Comment by ikjo93** [comment]
3월 한 달 동안 스터디를 진행하면서, 백준 알고리즘 문제를 일주일에 5 문제씩 꾸준히 풀어냄으로써, 알고리즘 문제 풀이 역량을 한 층 더 강화할 수 있었습니다. 

특히, 3월에는 SSAFY의 웹 교육 과정을 중점적으로 학습했었기에, 알고리즘 문제 풀이에 소홀해질 수도 있었는데, 이러한 스터디를 통해 책임 의식을 가질 수 있어 문제 풀이를 마무리 할 수 있었다고 생각합니다. 아울러, 스터디 활동간 SSAFY의 오프라인 공간과 매주 목요일 정기회의(Webex) 시간을 통해 스터디원들과 함께 문제에 접근 방법을 공유하고 어려운 문제를 만나더라도 스터디원들과 함께 논의할 수 있어 알고리즘 학습에 시너지 효과를 낼 수 있었습니다. 

이제 벌써 3월이 지나가고 SSAFY의 1학기 과정 절반이 지나갔는데, 남은 시간 역시 후회하지 않도록 현재의 알고리즘 스터디를 4월과 5월에도 꾸준히 지속하여 스터디원들과 함께 보다 나은 학습 성과물을 만들어내고자 합니다.

**Comment by junho112** [comment]
각자 출제한 백준 알고리즘 문제를 일주일에 5문제 씩 강제적으로 풀면서 다양한 알고리즘에 대해 적응할 수 있었습니다. 특히 모의 역량테스트 이후 소홀해 질 수 있었던 알고리즘 공부를 스터디원들끼리 함께 해쳐나가면서 알고리즘 공부에 더욱 몰두 할 수 있었습니다. 
  또한 다양한 기업들의 코딩테스트 정보나 역량테스트 B형 시험 정보 등 코딩테스트와 관련된 많은 꿀팁이나 일정들을 팀원들끼리 공유하면 취뽀에 한단계 더 다가갈 수 있었습니다. 
  4월에는 수업 때 배우는 동적계획법(DP) 알고리즘을 심화학습하며 많은 코테 준비생들이 어려워하는 DP를 정복할 계획입니다.

**Comment by rnrlgus** [comment]
2월에 싸피의 알고리즘 집중 학습 기간을 가진 후, 알고리즘 문제 풀이 폼이 상당히 올라왔다는 느낌을 가졌습니다. 이후 3월에 웹 과정을 학습하며 알고리즘 스터디를 병행한 덕에, 전달에 올려놨던 폼을 유지할 수 있었습니다. 또한 팀원들과 코드 리뷰 및 주간 회의 활동을 통해 더 다양한 관점을 가질 수 있었습니다. 하지만 무엇보다도 혼자서 학습을 할 때는 얻을 수 없는, 팀원들과 함께 함으로써 얻을 수 있었던 동기부여가 무엇보다 영향이 컸다고 느꼈습니다. 함께 성장하는 것을 즐기게 해준 팀원들과 스터디 활동에 감사함을 느꼈습니다. 
앞으로도 스터디 활동을 통해 팀원들과 함께 꾸준히 성장할 수 있도록 노력할 것입니다.

**Comment by BBaeGGom-sk** [comment]
알고리즘에 대해 거의 모르는 상태로 싸피 과정을 시작하게 되었을때는 너무 막막한 마음만 있었습니다. 또 알고리즘 스터디를 하는 것 또한 스터디원들에게 민폐만 끼치는 것이 아닐까 하는 걱정이 많았습니다. 사실 당연하게도 각자의 실력차이가 있었지만 오히려 앞선 걱정과는 반대로 부족한 부분을 서로 채워주고 이끌어주면서 win-win 할 수 있는 시너지 효과가 생겼고, 용기와 자신감을 얻을 수 있었습니다. 결과적으로 스터디를 시작하고나니 단기간에 골드 문제들까지 풀 수 있는 수준으로 올라갈 수 있었습니다. 
매주 목요일에 webex를 통한 정기리뷰 시간에 각자의 코드를 다른 사람에게 설명하면서 나의 코드를 한번 더 되돌아보거나 좀 더 명확하게 이해할 수 있어서 좋았고, 나와는 다른 관점에서 생각한 다른 사람의 설명을 들으면서 유연하게 사고하는 능력을 한층 더 성장 시킬 수 있었습니다.
무엇보다 좋은 스터디원들과 함께했던 시간이 저에겐 매우 의미있고 감사한 시간이였습니다. 더 나은 스터디원이 되기 위해 노력하겠습니다. 그리고 앞으로도 꾸준히 알고리즘 스터디를 지속하여 각자 좋은 결과로 나타났으면 좋겠습니다. 16반 JAVA 2팀 화이팅 !!

**Comment by shin197** [comment]
평소에 알고리즘 문제 푸는걸 수능 국영수랑 같은 차원의 일 정도로 생각하고 알고리즘을 멀리 했었습니다. 국영수와 다른 점이 있다면 자신이 일일히 푼 문제를 블로그에 올리려고 하는 사람이 있다는 정도려나요. 하지만 여러 회사에서 코딩 테스트를 중요시하기 시작하고 그 수준도 점점 높아져가고 있는데, 이걸 무조건 거스를 수는 없는게 현실이자 시대의 흐름이라고 생각하여 스터디에 들어가게 되었습니다만, 역시 익숙하지 않은 분야를 꾸준히 하는 건 어려운 것 같습니다.

현재 나로써는 풀지 못하는 문제가 있어보인다는 게 하나, 스터디에 들어왔다 한들 알고리즘에 대한 인식이 바뀌지 않았다는 점이 둘, 싸피 과정을 하는거 자체가 급급한게 셋, 그 외 등등이 겹치다보니 평소에는 알고리즘 문제들을 쳐다보지도 않다가, 모임이 있는 목요일 직전에 문제들을 최대한 많이 푸는 식으로 벼락치기 하듯이 풀고 스터디 모임이 끝나자마자 잠을 청하곤 했습니다.

6주동안 힘에 부쳐가는 자신을 느껴가면서 깨달은 게 있다면, 처음엔 정말 하긴 싫었던 알고리즘이었지만, 이러한 루틴이 습관이 되가면서 점점 알고리즘을 하는데 의지가 덜 필요해졌다는 것입니다. 물론 어렵고 힘든건 변하지 않지만, 일단 하다보면 동기부여가 생기는 것 같습니다. 또한 다른 스터디원들도 열심히 하는 모습을 봐가면서 오래 갈 수 있었던 것 같습니다. 다른 분들이 열심히 하는 모습을 보자 하면, 스터디는 은근히 경쟁적인 분위기가 있어서 혼자 뒤쳐지는게 용서되지 않을것만 같은 생각이 드는 것 같습니다.

결국은 갈 길은 멀지만 지금까지 열심히 해온것 만으로도 스스로를 자랑스럽게 여깁니다. 스터디에서 제일 잘한다고는 추호도 생각하진 않지만 스스로 발전했다는 점만큼은 뿌듯하게 여겨도 된다고 생각합니다/

**Comment by junho112** [comment]
3월 스터디 회고 issue close
